<Project Sdk="MSBuild.Sdk.Extras/1.6.61">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ExtrasEnableWpfProjectSetup>true</ExtrasEnableWpfProjectSetup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="References\**" />
    <EmbeddedResource Remove="References\**" />
    <None Remove="References\**" />
    <Page Remove="References\**" />
    <_SettingsFiles Remove="References\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove=".gitattributes" />
    <None Remove=".gitignore" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MessageTemplates">
      <HintPath>References\MessageTemplates.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>References\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="SmartLogging">
      <HintPath>References\SmartLogging.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>